--    Openbravo POS is a point of sales application designed for touch screens.
--    Copyright (C) 2007-2010 Openbravo, S.L.
--    http://sourceforge.net/projects/openbravopos
--
--    This file is part of Openbravo POS.
--
--    Openbravo POS is free software: you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation, either version 3 of the License, or
--    (at your option) any later version.
--
--    Openbravo POS is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

-- Database initial data for POSTGRESQL
-- v2.30.2

INSERT INTO OBPOS_APPLICATIONS(OBPOS_APPLICATIONS_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, VERSION)
    VALUES($APP_ID{}, $CONFIG_SYSTEMCLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, $APP_NAME{}, $APP_VERSION{});

INSERT INTO OBPOS_ROLES(OBPOS_ROLES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, PERMISSIONS)
    VALUES('0', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Administrator role', $FILE{/com/openbravo/pos/templates/Role.Administrator.xml} );
INSERT INTO OBPOS_ROLES(OBPOS_ROLES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, PERMISSIONS)
    VALUES('1', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Manager role', $FILE{/com/openbravo/pos/templates/Role.Manager.xml} );
INSERT INTO OBPOS_ROLES(OBPOS_ROLES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, PERMISSIONS)
    VALUES('2', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Employee role', $FILE{/com/openbravo/pos/templates/Role.Employee.xml} );
INSERT INTO OBPOS_ROLES(OBPOS_ROLES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, PERMISSIONS)
    VALUES('3', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Guest role', $FILE{/com/openbravo/pos/templates/Role.Guest.xml} );

INSERT INTO OBPOS_PEOPLE(OBPOS_PEOPLE_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, APPPASSWORD, OBPOS_ROLES_ID, VISIBLE, IMAGE)
    VALUES ('0', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Administrator', NULL, '0', 'Y', NULL);
INSERT INTO OBPOS_PEOPLE(OBPOS_PEOPLE_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, APPPASSWORD, OBPOS_ROLES_ID, VISIBLE, IMAGE)
    VALUES ('1', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Manager', NULL, '1', 'Y', NULL);
INSERT INTO OBPOS_PEOPLE(OBPOS_PEOPLE_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, APPPASSWORD, OBPOS_ROLES_ID, VISIBLE, IMAGE)
    VALUES ('2', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Employee', NULL, '2', 'Y', NULL);
INSERT INTO OBPOS_PEOPLE(OBPOS_PEOPLE_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, APPPASSWORD, OBPOS_ROLES_ID, VISIBLE, IMAGE)
    VALUES ('3', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Guest', NULL, '3', 'Y', NULL);

INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('0', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.Start', 0, $FILE{/com/openbravo/pos/templates/Printer.Start.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('1', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.Ticket', 0, $FILE{/com/openbravo/pos/templates/Printer.Ticket.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('2', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.Ticket2', 0, $FILE{/com/openbravo/pos/templates/Printer.Ticket2.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('3', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.TicketPreview', 0, $FILE{/com/openbravo/pos/templates/Printer.TicketPreview.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('4', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.TicketTotal', 0, $FILE{/com/openbravo/pos/templates/Printer.TicketTotal.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('5', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.OpenDrawer', 0, $FILE{/com/openbravo/pos/templates/Printer.OpenDrawer.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('6', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.Ticket.Logo', 1, $FILE{/com/openbravo/pos/templates/Printer.Ticket.Logo.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('7', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.TicketLine', 0, $FILE{/com/openbravo/pos/templates/Printer.TicketLine.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('8', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.CloseCash', 0, $FILE{/com/openbravo/pos/templates/Printer.CloseCash.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('9', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Window.Logo', 1, $FILE{/com/openbravo/pos/templates/Window.Logo.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('10', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Window.Title', 0, $FILE{/com/openbravo/pos/templates/Window.Title.txt});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('11', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Ticket.Buttons', 0, $FILE{/com/openbravo/pos/templates/Ticket.Buttons.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('12', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Ticket.Line', 0, $FILE{/com/openbravo/pos/templates/Ticket.Line.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('13', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.Inventory', 0, $FILE{/com/openbravo/pos/templates/Printer.Inventory.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('14', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Menu.Root', 0, $FILE{/com/openbravo/pos/templates/Menu.Root.txt});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('15', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.CustomerPaid', 0, $FILE{/com/openbravo/pos/templates/Printer.CustomerPaid.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('16', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.CustomerPaid2', 0, $FILE{/com/openbravo/pos/templates/Printer.CustomerPaid2.xml});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('17', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'payment.cash', 0, $FILE{/com/openbravo/pos/templates/payment.cash.txt});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('18', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'banknote.50euro', 1, $FILE{/com/openbravo/pos/templates/banknote.50euro.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('19', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'banknote.20euro', 1, $FILE{/com/openbravo/pos/templates/banknote.20euro.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('20', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'banknote.10euro', 1, $FILE{/com/openbravo/pos/templates/banknote.10euro.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('21', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'banknote.5euro', 1, $FILE{/com/openbravo/pos/templates/banknote.5euro.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('22', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'coin.2euro', 1, $FILE{/com/openbravo/pos/templates/coin.2euro.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('23', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'coin.1euro', 1, $FILE{/com/openbravo/pos/templates/coin.1euro.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('24', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'coin.50cent', 1, $FILE{/com/openbravo/pos/templates/coin.50cent.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('25', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'coin.20cent', 1, $FILE{/com/openbravo/pos/templates/coin.20cent.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('26', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'coin.10cent', 1, $FILE{/com/openbravo/pos/templates/coin.10cent.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('27', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'coin.5cent', 1, $FILE{/com/openbravo/pos/templates/coin.5cent.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('28', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'coin.2cent', 1, $FILE{/com/openbravo/pos/templates/coin.2cent.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('29', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'coin.1cent', 1, $FILE{/com/openbravo/pos/templates/coin.1cent.png});
INSERT INTO OBPOS_RESOURCES(OBPOS_RESOURCES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, RESTYPE, CONTENT) VALUES('30', $CONFIG_CLIENT{}, $CONFIG_SUPERORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Printer.PartialCash', 0, $FILE{/com/openbravo/pos/templates/Printer.PartialCash.xml});

INSERT INTO OBPOS_CATEGORIES(OBPOS_CATEGORIES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME) VALUES ('000', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Category Standard');

-- INSERT INTO OBPOS_TAXCATEGORIES(OBPOS_TAXCATEGORIES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME) VALUES ('000', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Tax Exempt');
-- INSERT INTO OBPOS_TAXCATEGORIES(OBPOS_TAXCATEGORIES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME) VALUES ('001', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Tax Standard');

-- INSERT INTO OBPOS_TAXES(OBPOS_TAXES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, OBPOS_TAXCATEGORIES_ID, OBPOS_TAXCUSTCATEGORIES_ID, PARENT_OBPOS_TAXES_ID, RATE, RATECASCADE, RATEORDER) VALUES ('000', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Tax Exempt', '000', NULL, NULL, 0, 'N', NULL);
-- INSERT INTO OBPOS_TAXES(OBPOS_TAXES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, OBPOS_TAXCATEGORIES_ID, OBPOS_TAXCUSTCATEGORIES_ID, PARENT_OBPOS_TAXES_ID, RATE, RATECASCADE, RATEORDER) VALUES ('001', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Tax Standard', '001', NULL, NULL, 0.10, 'N', NULL);

INSERT INTO OBPOS_LOCATIONS(OBPOS_LOCATIONS_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME,ADDRESS) VALUES('0', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'General', NULL);

INSERT INTO OBPOS_FLOORS(OBPOS_FLOORS_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, IMAGE) VALUES ('0', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Restaurant floor', $FILE{/com/openbravo/pos/templates/restaurantsample.png});

INSERT INTO OBPOS_PLACES(OBPOS_PLACES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, X, Y, OBPOS_FLOORS_ID) VALUES ('1', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Table 1', 133, 151, '0');
INSERT INTO OBPOS_PLACES(OBPOS_PLACES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, X, Y, OBPOS_FLOORS_ID) VALUES ('2', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Table 2', 532, 151, '0');
INSERT INTO OBPOS_PLACES(OBPOS_PLACES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, X, Y, OBPOS_FLOORS_ID) VALUES ('3', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Table 3', 133, 264, '0');
INSERT INTO OBPOS_PLACES(OBPOS_PLACES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, X, Y, OBPOS_FLOORS_ID) VALUES ('4', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Table 4', 266, 264, '0');
INSERT INTO OBPOS_PLACES(OBPOS_PLACES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, X, Y, OBPOS_FLOORS_ID) VALUES ('5', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Table 5', 399, 264, '0');
INSERT INTO OBPOS_PLACES(OBPOS_PLACES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, X, Y, OBPOS_FLOORS_ID) VALUES ('6', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Table 6', 532, 264, '0');
INSERT INTO OBPOS_PLACES(OBPOS_PLACES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, X, Y, OBPOS_FLOORS_ID) VALUES ('7', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Table 7', 133, 377, '0');
INSERT INTO OBPOS_PLACES(OBPOS_PLACES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, X, Y, OBPOS_FLOORS_ID) VALUES ('8', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Table 8', 266, 377, '0');
INSERT INTO OBPOS_PLACES(OBPOS_PLACES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, X, Y, OBPOS_FLOORS_ID) VALUES ('9', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Table 9', 399, 377, '0');
INSERT INTO OBPOS_PLACES(OBPOS_PLACES_ID, AD_CLIENT_ID, AD_ORG_ID, CREATEDBY, UPDATEDBY, NAME, X, Y, OBPOS_FLOORS_ID) VALUES ('10', $CONFIG_CLIENT{}, $CONFIG_ORG{}, $CONFIG_USER{}, $CONFIG_USER{}, 'Table 10', 532, 377, '0');
