--    Openbravo POS is a point of sales application designed for touch screens.
--    Copyright (C) 2007-2010 Openbravo, S.L.
--    http://sourceforge.net/projects/openbravopos
--
--    This file is part of Openbravo POS.
--
--    Openbravo POS is free software: you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation, either version 3 of the License, or
--    (at your option) any later version.
--
--    Openbravo POS is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

-- Database initial script for POSTGRESQL
-- v2.30.2

DROP TABLE IF EXISTS OBPOS_SHAREDTICKETS CASCADE;
DROP TABLE IF EXISTS OBPOS_RESERVATION_CUSTOMERS CASCADE;
DROP TABLE IF EXISTS OBPOS_RESERVATIONS CASCADE;
DROP TABLE IF EXISTS OBPOS_PLACES CASCADE;
DROP TABLE IF EXISTS OBPOS_FLOORS CASCADE;
DROP TABLE IF EXISTS OBPOS_TAXLINES CASCADE;
DROP TABLE IF EXISTS OBPOS_PAYMENTS CASCADE;
DROP TABLE IF EXISTS OBPOS_TICKETLINES CASCADE;
DROP TABLE IF EXISTS OBPOS_TICKETS CASCADE;
DROP TABLE IF EXISTS OBPOS_RECEIPTS CASCADE;
DROP TABLE IF EXISTS OBPOS_CLOSEDCASH CASCADE;
DROP TABLE IF EXISTS OBPOS_STOCKCURRENT CASCADE;
DROP TABLE IF EXISTS OBPOS_STOCKLEVEL CASCADE;
DROP TABLE IF EXISTS OBPOS_STOCKDIARY CASCADE;
DROP TABLE IF EXISTS OBPOS_LOCATIONS CASCADE;
DROP TABLE IF EXISTS OBPOS_PRODUCTS_COM CASCADE;
DROP TABLE IF EXISTS OBPOS_PRODUCTS_CAT CASCADE;
DROP TABLE IF EXISTS OBPOS_PRODUCTS CASCADE;
DROP TABLE IF EXISTS OBPOS_ATTRIBUTEINSTANCE CASCADE;
DROP TABLE IF EXISTS OBPOS_ATTRIBUTESETINSTANCE CASCADE;
DROP TABLE IF EXISTS OBPOS_ATTRIBUTEUSE CASCADE;
DROP TABLE IF EXISTS OBPOS_ATTRIBUTESET CASCADE;
DROP TABLE IF EXISTS OBPOS_ATTRIBUTEVALUE CASCADE;
DROP TABLE IF EXISTS OBPOS_ATTRIBUTE CASCADE;
-- DROP TABLE IF EXISTS OBPOS_TAXES CASCADE;
-- DROP TABLE IF EXISTS OBPOS_TAXCATEGORIES CASCADE;
DROP TABLE IF EXISTS OBPOS_CATEGORIES CASCADE;
DROP TABLE IF EXISTS OBPOS_CUSTOMERS CASCADE;
-- DROP TABLE IF EXISTS OBPOS_TAXCUSTCATEGORIES CASCADE;
DROP TABLE IF EXISTS OBPOS_RESOURCES CASCADE;
DROP TABLE IF EXISTS OBPOS_PEOPLE CASCADE;
DROP TABLE IF EXISTS OBPOS_ROLES CASCADE;
DROP TABLE IF EXISTS OBPOS_APPLICATIONS CASCADE;
DROP SEQUENCE IF EXISTS OBPOS_TICKETSNUM;
DROP SEQUENCE IF EXISTS OBPOS_TICKETSNUM_REFUND;
DROP SEQUENCE IF EXISTS OBPOS_TICKETSNUM_PAYMENT;

CREATE TABLE OBPOS_APPLICATIONS (
    OBPOS_APPLICATIONS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    VERSION VARCHAR(1024) NOT NULL,
    CONSTRAINT OBPOS_APP_PK PRIMARY KEY (OBPOS_APPLICATIONS_ID),
    CONSTRAINT OBPOS_APP_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_APP_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_APP_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
);

CREATE TABLE OBPOS_ROLES (
    OBPOS_ROLES_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    PERMISSIONS BYTEA,
    CONSTRAINT OBPOS_ROLES_PK PRIMARY KEY (OBPOS_ROLES_ID),
    CONSTRAINT OBPOS_ROLES_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_ROLES_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_ROLES_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
);
CREATE UNIQUE INDEX OBPOS_ROLES_NAME ON OBPOS_ROLES(NAME);

CREATE OR REPLACE VIEW OBPOS_ROLESVIEW AS
SELECT OBPOS_ROLE_ID, AD_CLIENT_ID, AD_ORG_ID, ISACTIVE, CREATED, CREATEDBY, UPDATED, UPDATEDBY, NAME FROM OBPOS_ROLES;

CREATE TABLE OBPOS_PEOPLE (
    OBPOS_PEOPLE_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    APPPASSWORD VARCHAR(1024),
    CARD VARCHAR(1024),
    OBPOS_ROLES_ID VARCHAR(32) NOT NULL,
    VISIBLE CHAR(1) NOT NULL,
    IMAGE BYTEA,
    CONSTRAINT OBPOS_PEOPLE_PK PRIMARY KEY (OBPOS_PEOPLE_ID),
    CONSTRAINT OBPOS_PEOPLE_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_PEOPLE_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_PEOPLE_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_PEOPLE_ROLES FOREIGN KEY (OBPOS_ROLES_ID) REFERENCES OBPOS_ROLES(OBPOS_ROLES_ID)
);
CREATE UNIQUE INDEX OBPOS_PEOPLE_NAME ON OBPOS_PEOPLE(NAME);
CREATE INDEX OBPOS_PEOPLE_CARD ON OBPOS_PEOPLE(CARD);

CREATE OR REPLACE VIEW OBPOS_PEOPLEVIEW AS
SELECT OBPOS_PEOPLE_ID, AD_CLIENT_ID, AD_ORG_ID, ISACTIVE, CREATED, CREATEDBY, UPDATED, UPDATEDBY, NAME FROM OBPOS_PEOPLE;

CREATE TABLE OBPOS_RESOURCES (
    OBPOS_RESOURCES_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    RESTYPE NUMERIC(10,0) NOT NULL,
    CONTENT BYTEA,
    CONSTRAINT OBPOS_RESOURCES_PK PRIMARY KEY (OBPOS_RESOURCES_ID),
    CONSTRAINT OBPOS_RESOURCES_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_RESOURCES_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_RESOURCES_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
);
CREATE UNIQUE INDEX OBPOS_RESOURCES_NAME ON OBPOS_RESOURCES(NAME);


CREATE TABLE OBPOS_CLOSEDCASH (
    OBPOS_CLOSEDCASH_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    HOST VARCHAR(1024) NOT NULL,
    HOSTSEQUENCE NUMERIC(10,0) NOT NULL,
    DATESTART TIMESTAMP NOT NULL,
    DATEEND TIMESTAMP,
    CONSTRAINT OBPOS_CLOSEDCASH_PK PRIMARY KEY(OBPOS_CLOSEDCASH_ID),
    CONSTRAINT OBPOS_CLOSEDCASH_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_CLOSEDCASH_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_CLOSEDCASH_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
);
CREATE INDEX OBPOS_CLOSEDCASH_DATESTART ON OBPOS_CLOSEDCASH(DATESTART);
CREATE UNIQUE INDEX OBPOS_CLOSEDCASH_HOSTSEQ ON OBPOS_CLOSEDCASH(HOST, HOSTSEQUENCE);

CREATE TABLE OBPOS_CUSTOMERS (
    OBPOS_CUSTOMERS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    SEARCHKEY VARCHAR(1024) NOT NULL,
    TAXID VARCHAR(1024),
    NAME VARCHAR(1024) NOT NULL,
    C_BP_TAXCATEGORY_ID VARCHAR(32),
    CARD VARCHAR(1024),
    MAXDEBT NUMERIC DEFAULT 0 NOT NULL,
    ADDRESS VARCHAR(1024),
    ADDRESS2 VARCHAR(1024),
    POSTAL VARCHAR(1024),
    CITY VARCHAR(1024),
    REGION VARCHAR(1024),
    COUNTRY VARCHAR(1024),
    FIRSTNAME VARCHAR(1024),
    LASTNAME VARCHAR(1024),
    EMAIL VARCHAR(1024),
    PHONE VARCHAR(1024),
    PHONE2 VARCHAR(1024),
    FAX VARCHAR(1024),
    NOTES VARCHAR(1024),
    VISIBLE CHAR(1) DEFAULT 'Y' NOT NULL,
    CURDATE TIMESTAMP,
    CURDEBT NUMERIC,
    CONSTRAINT OBPOS_CUSTOMERS_PK PRIMARY KEY (OBPOS_CUSTOMERS_ID),
    CONSTRAINT OBPOS_CUSTOMERS_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_CUSTOMERS_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_CUSTOMERS_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_CUSTOMERS_BPTAXCAT FOREIGN KEY (C_BP_TAXCATEGORY_ID) REFERENCES C_BP_TAXCATEGORY(C_BP_TAXCATEGORY_ID)
);
CREATE UNIQUE INDEX OBPOS_CUSTOMERS_SEARCHKEY ON OBPOS_CUSTOMERS(SEARCHKEY);
CREATE INDEX OBPOS_CUSTOMERS_TAXID ON OBPOS_CUSTOMERS(TAXID);
CREATE INDEX OBPOS_CUSTOMERS_NAME ON OBPOS_CUSTOMERS(NAME);
CREATE INDEX OBPOS_CUSTOMERS_CARD ON OBPOS_CUSTOMERS(CARD);

CREATE TABLE OBPOS_CATEGORIES (
    OBPOS_CATEGORIES_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    PARENT_OBPOS_CATEGORIES_ID VARCHAR(32),
    IMAGE BYTEA,
    CONSTRAINT OBPOS_CATEGORIES_PK PRIMARY KEY(OBPOS_CATEGORIES_ID),
    CONSTRAINT OBPOS_CATEGORIES_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_CATEGORIES_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_CATEGORIES_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_CATEGORIES_PARENT FOREIGN KEY (PARENT_OBPOS_CATEGORIES_ID) REFERENCES OBPOS_CATEGORIES(OBPOS_CATEGORIES_ID)
);
CREATE UNIQUE INDEX OBPOS_CATEGORIES_NAME ON OBPOS_CATEGORIES(NAME);

CREATE TABLE OBPOS_ATTRIBUTE (
    OBPOS_ATTRIBUTE_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    CONSTRAINT OBPOS_ATTRIBUTE_PK PRIMARY KEY (OBPOS_ATTRIBUTE_ID),
    CONSTRAINT OBPOS_ATTRIBUTE_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_ATTRIBUTE_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_ATTRIBUTE_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
);

CREATE TABLE OBPOS_ATTRIBUTEVALUE (
    OBPOS_ATTRIBUTEVALUE_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_ATTRIBUTE_ID VARCHAR(32) NOT NULL,
    VALUE VARCHAR(1024),
    CONSTRAINT OBPOS_ATTVAL_PK PRIMARY KEY (OBPOS_ATTRIBUTEVALUE_ID),
    CONSTRAINT OBPOS_ATTVAL_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_ATTVAL_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_ATTVAL_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_ATTVAL_ATTRIBUTE FOREIGN KEY (OBPOS_ATTRIBUTE_ID) REFERENCES OBPOS_ATTRIBUTE(OBPOS_ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE OBPOS_ATTRIBUTESET (
    OBPOS_ATTRIBUTESET_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    CONSTRAINT OBPOS_ATTSET_PK PRIMARY KEY (OBPOS_ATTRIBUTESET_ID),
    CONSTRAINT OBPOS_ATTSET_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_ATTSET_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_ATTSET_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
);

CREATE TABLE OBPOS_ATTRIBUTEUSE (
    OBPOS_ATTRIBUTEUSE_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_ATTRIBUTESET_ID VARCHAR(32) NOT NULL,
    OBPOS_ATTRIBUTE_ID VARCHAR(32) NOT NULL,
    LINENO NUMERIC(10,0),
    CONSTRAINT OBPOS_ATTUSE_PK PRIMARY KEY (OBPOS_ATTRIBUTEUSE_ID),
    CONSTRAINT OBPOS_ATTUSE_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_ATTUSE_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_ATTUSE_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_ATTUSE_ATTSET FOREIGN KEY (OBPOS_ATTRIBUTESET_ID) REFERENCES OBPOS_ATTRIBUTESET(OBPOS_ATTRIBUTESET_ID) ON DELETE CASCADE,
    CONSTRAINT OBPOS_ATTUSE_ATTRIBUTE FOREIGN KEY (OBPOS_ATTRIBUTE_ID) REFERENCES OBPOS_ATTRIBUTE(OBPOS_ATTRIBUTE_ID)
);
CREATE UNIQUE INDEX OBPOS_ATTRIBUTEUSE_LINENO ON OBPOS_ATTRIBUTEUSE(OBPOS_ATTRIBUTESET_ID, LINENO);

CREATE TABLE OBPOS_ATTRIBUTESETINSTANCE (
    OBPOS_ATTRIBUTESETINSTANCE_ID VARCHAR(256) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_ATTRIBUTESET_ID VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    CONSTRAINT OBPOS_ATTSETINST_PK PRIMARY KEY (OBPOS_ATTRIBUTESETINSTANCE_ID),
    CONSTRAINT OBPOS_ATTSETINST_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_ATTSETINST_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_ATTSETINST_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_ATTSETINST_SET FOREIGN KEY (OBPOS_ATTRIBUTESET_ID) REFERENCES OBPOS_ATTRIBUTESET(OBPOS_ATTRIBUTESET_ID) ON DELETE CASCADE
);

CREATE TABLE OBPOS_ATTRIBUTEINSTANCE (
    OBPOS_ATTRIBUTEINSTANCE_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_ATTRIBUTESETINSTANCE_ID VARCHAR(256) NOT NULL,
    OBPOS_ATTRIBUTE_ID VARCHAR(256) NOT NULL,
    VALUE VARCHAR(1024),
    CONSTRAINT OBPOS_ATTINST_PK PRIMARY KEY (OBPOS_ATTRIBUTEINSTANCE_ID),
    CONSTRAINT OBPOS_ATTINST_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_ATTINST_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_ATTINST_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_ATTINST_SET FOREIGN KEY (OBPOS_ATTRIBUTESETINSTANCE_ID) REFERENCES OBPOS_ATTRIBUTESETINSTANCE(OBPOS_ATTRIBUTESETINSTANCE_ID) ON DELETE CASCADE,
    CONSTRAINT OBPOS_ATTINST_ATT FOREIGN KEY (OBPOS_ATTRIBUTE_ID) REFERENCES OBPOS_ATTRIBUTE(OBPOS_ATTRIBUTE_ID)
);

CREATE TABLE OBPOS_PRODUCTS (
    OBPOS_PRODUCTS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    REFERENCE VARCHAR(1024) NOT NULL,
    CODE VARCHAR(1024) NOT NULL,
    CODETYPE VARCHAR(1024),
    NAME VARCHAR(1024) NOT NULL,
    PRICEBUY NUMERIC NOT NULL,
    PRICESELL NUMERIC NOT NULL,
    OBPOS_CATEGORIES_ID VARCHAR(32) NOT NULL,
    C_TAXCATEGORY_ID VARCHAR(32) NOT NULL,
    OBPOS_ATTRIBUTESET_ID VARCHAR(32),
    STOCKCOST NUMERIC,
    STOCKVOLUME NUMERIC,
    IMAGE BYTEA,
    ISCOM CHAR(1) DEFAULT 'N' NOT NULL,
    ISSCALE CHAR(1) DEFAULT 'N' NOT NULL,
    ATTRIBUTES BYTEA,
    CONSTRAINT OBPOS_PRODUCTS_PK PRIMARY KEY (OBPOS_PRODUCTS_ID),
    CONSTRAINT OBPOS_PRODUCTS_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_PRODUCTS_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_PRODUCTS_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_PRODUCTS_CAT FOREIGN KEY (OBPOS_CATEGORIES_ID) REFERENCES OBPOS_CATEGORIES(OBPOS_CATEGORIES_ID),
    CONSTRAINT OBPOS_PRODUCTS_TAXCAT FOREIGN KEY (C_TAXCATEGORY_ID) REFERENCES C_TAXCATEGORY(C_TAXCATEGORY_ID),
    CONSTRAINT OBPOS_PRODUCTS_ATTSET FOREIGN KEY (OBPOS_ATTRIBUTESET_ID) REFERENCES OBPOS_ATTRIBUTESET(OBPOS_ATTRIBUTESET_ID)
);
CREATE UNIQUE INDEX OBPOS_PRODUCTS_REF ON OBPOS_PRODUCTS(REFERENCE);
CREATE UNIQUE INDEX OBPOS_PRODUCTS_CODE ON OBPOS_PRODUCTS(CODE);
CREATE UNIQUE INDEX OBPOS_PRODUCTS_NAME ON OBPOS_PRODUCTS(NAME);

ALTER TABLE M_PRODUCT ADD EM_OBPOS_PRODUCTAUX_ID VARCHAR(32);
ALTER TABLE M_PRODUCT ADD CONSTRAINT EM_OBPOS_PRODUCTAUX FOREIGN KEY (EM_OBPOS_PRODUCTAUX_ID) REFERENCES M_PRODUCT(M_PRODUCT_ID);
ALTER TABLE M_PRODUCT ADD EM_OBPOS_SCALE CHAR(1) DEFAULT 'N' NOT NULL;
ALTER TABLE M_PRODUCT ADD CONSTRAINT EM_OBPOS_SCALE_CHK CHECK (EM_OBPOS_SCALE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]));
ALTER TABLE M_PRODUCT ADD EM_OBPOS_CATEGORIES_ID VARCHAR(32);
ALTER TABLE M_PRODUCT ADD CONSTRAINT EM_OBPOS_PRODUCTS_CAT FOREIGN KEY (EM_OBPOS_CATEGORIES_ID) REFERENCES OBPOS_CATEGORIES(OBPOS_CATEGORIES_ID);
ALTER TABLE M_PRODUCT ADD EM_OBPOS_ATTRIBUTES TEXT;
ALTER TABLE M_PRODUCT ADD EM_OBPOS_LINE NUMERIC(10,0);

CREATE TABLE OBPOS_PRODUCTS_CAT (
    OBPOS_PRODUCTS_CAT_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_PRODUCTS_ID VARCHAR(32) NOT NULL,
    CATORDER NUMERIC(10,0),
    CONSTRAINT OBPOS_PRODS_CAT_PK PRIMARY KEY (OBPOS_PRODUCTS_CAT_ID),
    CONSTRAINT OBPOS_PRODS_CAT_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_PRODS_CAT_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_PRODS_CAT_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_PRODS_CAT_PRODS FOREIGN KEY (OBPOS_PRODUCTS_ID) REFERENCES OBPOS_PRODUCTS(OBPOS_PRODUCTS_ID)
);
CREATE INDEX OBPOS_PRODUCTS_CATORDER ON OBPOS_PRODUCTS_CAT(CATORDER);

CREATE TABLE OBPOS_PRODUCTS_COM (
    OBPOS_PRODUCTS_COM_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_PRODUCTS_ID VARCHAR(32) NOT NULL,
    RELATED_OBPOS_PRODUCTS_ID VARCHAR(32) NOT NULL,
    CONSTRAINT OBPOS_PRODS_COM_PK PRIMARY KEY (OBPOS_PRODUCTS_COM_ID),
    CONSTRAINT OBPOS_PRODS_COM_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_PRODS_COM_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_PRODS_COM_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_PRODS_COM_PRODS FOREIGN KEY (OBPOS_PRODUCTS_ID) REFERENCES OBPOS_PRODUCTS(OBPOS_PRODUCTS_ID),
    CONSTRAINT OBPOS_PRODS_COM_RELPRODS FOREIGN KEY (RELATED_OBPOS_PRODUCTS_ID) REFERENCES OBPOS_PRODUCTS(OBPOS_PRODUCTS_ID)
);
CREATE UNIQUE INDEX OBPOS_PRODUCTS_COM_PRODS ON OBPOS_PRODUCTS_COM(OBPOS_PRODUCTS_ID, RELATED_OBPOS_PRODUCTS_ID);

CREATE TABLE OBPOS_LOCATIONS (
    OBPOS_LOCATIONS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    ADDRESS VARCHAR(1024),
    CONSTRAINT OBPOS_LOCATIONS_PK PRIMARY KEY (OBPOS_LOCATIONS_ID),
    CONSTRAINT OBPOS_LOCATIONS_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_LOCATIONS_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_LOCATIONS_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
);
CREATE UNIQUE INDEX OBPOS_LOCATIONS_NAME ON OBPOS_LOCATIONS(NAME);

CREATE TABLE OBPOS_STOCKDIARY (
    OBPOS_STOCKDIARY_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    DATENEW TIMESTAMP NOT NULL,
    REASON NUMERIC(10,0) NOT NULL,
    OBPOS_LOCATIONS_ID VARCHAR(32) NOT NULL,
    OBPOS_PRODUCTS_ID VARCHAR(32) NOT NULL,
    OBPOS_ATTRIBUTESETINSTANCE_ID VARCHAR(32),
    UNITS NUMERIC NOT NULL,
    PRICE NUMERIC NOT NULL,
    CONSTRAINT OBPOS_STOCKDIARY_PK PRIMARY KEY (OBPOS_STOCKDIARY_ID),
    CONSTRAINT OBPOS_STOCKDIARY_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_STOCKDIARY_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_STOCKDIARY_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_STOCKDIARY_PRODS FOREIGN KEY (OBPOS_PRODUCTS_ID) REFERENCES OBPOS_PRODUCTS(OBPOS_PRODUCTS_ID),
    CONSTRAINT OBPOS_STOCKDIARY_ATTS FOREIGN KEY (OBPOS_ATTRIBUTESETINSTANCE_ID) REFERENCES OBPOS_ATTRIBUTESETINSTANCE(OBPOS_ATTRIBUTESETINSTANCE_ID),
    CONSTRAINT OBPOS_STOCKDIARY_LOCS FOREIGN KEY (OBPOS_LOCATIONS_ID) REFERENCES OBPOS_LOCATIONS(OBPOS_LOCATIONS_ID)
);
CREATE INDEX OBPOS_STOCKDIARY_DATENEW ON OBPOS_STOCKDIARY(DATENEW);

CREATE TABLE OBPOS_STOCKLEVEL (
    OBPOS_STOCKLEVEL_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_LOCATIONS_ID VARCHAR(256) NOT NULL,
    OBPOS_PRODUCTS_ID VARCHAR(32) NOT NULL,
    STOCKSECURITY NUMERIC,
    STOCKMAXIMUM NUMERIC,
    CONSTRAINT OBPOS_STOCKLEVEL_PK PRIMARY KEY (OBPOS_STOCKLEVEL_ID),
    CONSTRAINT OBPOS_STOCKLEVEL_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_STOCKLEVEL_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_STOCKLEVEL_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_STOCKLEVEL_PRODUCT FOREIGN KEY (OBPOS_PRODUCTS_ID) REFERENCES OBPOS_PRODUCTS(OBPOS_PRODUCTS_ID),
    CONSTRAINT OBPOS_STOCKLEVEL_LOCATION FOREIGN KEY (OBPOS_LOCATIONS_ID) REFERENCES OBPOS_LOCATIONS(OBPOS_LOCATIONS_ID)
);

CREATE TABLE OBPOS_STOCKCURRENT (
    OBPOS_STOCKCURRENT_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_LOCATIONS_ID VARCHAR(32) NOT NULL,
    OBPOS_PRODUCTS_ID VARCHAR(32) NOT NULL,
    OBPOS_ATTRIBUTESETINSTANCE_ID VARCHAR(32),
    UNITS NUMERIC NOT NULL,
    CONSTRAINT OBPOS_STKCURR_PK PRIMARY KEY (OBPOS_STOCKCURRENT_ID),
    CONSTRAINT OBPOS_STKCURR_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_STKCURR_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_STKCURR_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_STKCURR_PROD FOREIGN KEY (OBPOS_PRODUCTS_ID) REFERENCES OBPOS_PRODUCTS(OBPOS_PRODUCTS_ID),
    CONSTRAINT OBPOS_STKCURR_ATTS FOREIGN KEY (OBPOS_ATTRIBUTESETINSTANCE_ID) REFERENCES OBPOS_ATTRIBUTESETINSTANCE(OBPOS_ATTRIBUTESETINSTANCE_ID),
    CONSTRAINT OBPOS_STKCURR_LOCS FOREIGN KEY (OBPOS_LOCATIONS_ID) REFERENCES OBPOS_LOCATIONS(OBPOS_LOCATIONS_ID)
);
CREATE UNIQUE INDEX OBPOS_STOCKCURRENT_INX ON OBPOS_STOCKCURRENT(OBPOS_LOCATIONS_ID, OBPOS_PRODUCTS_ID, OBPOS_ATTRIBUTESETINSTANCE_ID);

CREATE TABLE OBPOS_RECEIPTS (
    OBPOS_RECEIPTS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_CLOSEDCASH_ID VARCHAR(32) NOT NULL,
    DATENEW TIMESTAMP NOT NULL,
    ATTRIBUTES BYTEA,
    CONSTRAINT OBPOS_RECEIPTS_PK PRIMARY KEY(OBPOS_RECEIPTS_ID),
    CONSTRAINT OBPOS_RECEIPTS_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_RECEIPTS_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_RECEIPTS_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_RECEIPTS_CLOSEDCASH FOREIGN KEY (OBPOS_CLOSEDCASH_ID) REFERENCES OBPOS_CLOSEDCASH(OBPOS_CLOSEDCASH_ID)
);
CREATE INDEX OBPOS_RECEIPTS_DATENEW ON OBPOS_RECEIPTS(DATENEW);
CREATE INDEX OBPOS_RECEIPTS_CLOSEDCASH ON OBPOS_RECEIPTS(OBPOS_CLOSEDCASH_ID);

CREATE TABLE OBPOS_TICKETS (
    OBPOS_TICKETS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    TICKETTYPE NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TICKETID NUMERIC(10,0) NOT NULL,
    OBPOS_PEOPLE_ID VARCHAR(32) NOT NULL,
    OBPOS_CUSTOMERS_ID VARCHAR(32),
    STATUS NUMERIC(10,0) DEFAULT 0 NOT NULL,
    CONSTRAINT OBPOS_TICKETS_PK PRIMARY KEY (OBPOS_TICKETS_ID),
    CONSTRAINT OBPOS_TICKETS_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_TICKETS_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_TICKETS_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_TICKETS_RECEIPTS FOREIGN KEY (OBPOS_TICKETS_ID) REFERENCES OBPOS_RECEIPTS(OBPOS_RECEIPTS_ID),
    CONSTRAINT OBPOS_TICKETS_PEOPLE FOREIGN KEY (OBPOS_PEOPLE_ID) REFERENCES OBPOS_PEOPLE(OBPOS_PEOPLE_ID),
    CONSTRAINT OBPOS_TICKETS_CUSTOMERS FOREIGN KEY (OBPOS_CUSTOMERS_ID) REFERENCES OBPOS_CUSTOMERS(OBPOS_CUSTOMERS_ID)
);
CREATE INDEX OBPOS_TICKETS_TICKET ON OBPOS_TICKETS(TICKETTYPE, TICKETID);

CREATE SEQUENCE OBPOS_TICKETSNUM START WITH 1;
CREATE SEQUENCE OBPOS_TICKETSNUM_REFUND START WITH 1;
CREATE SEQUENCE OBPOS_TICKETSNUM_PAYMENT START WITH 1;

CREATE TABLE OBPOS_TICKETLINES (
    OBPOS_TICKETLINES_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_TICKETS_ID VARCHAR(32) NOT NULL,
    LINE NUMERIC(10,0) NOT NULL,
    OBPOS_PRODUCTS_ID VARCHAR(32),
    OBPOS_ATTRIBUTESETINSTANCE_ID VARCHAR(32),
    UNITS NUMERIC NOT NULL,
    PRICE NUMERIC NOT NULL,
    C_TAX_ID VARCHAR(32) NOT NULL,
    ATTRIBUTES BYTEA,
    CONSTRAINT OBPOS_TICKETLINES_PK PRIMARY KEY (OBPOS_TICKETLINES_ID),
    CONSTRAINT OBPOS_TICKETLINES_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_TICKETLINES_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_TICKETLINES_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_TICKETLINES_TICKETS FOREIGN KEY (OBPOS_TICKETS_ID) REFERENCES OBPOS_TICKETS(OBPOS_TICKETS_ID),
    CONSTRAINT OBPOS_TICKETLINES_PRODS FOREIGN KEY (OBPOS_PRODUCTS_ID) REFERENCES OBPOS_PRODUCTS(OBPOS_PRODUCTS_ID),
    CONSTRAINT OBPOS_TICKETLINES_ATTS FOREIGN KEY (OBPOS_ATTRIBUTESETINSTANCE_ID) REFERENCES OBPOS_ATTRIBUTESETINSTANCE(OBPOS_ATTRIBUTESETINSTANCE_ID),
    CONSTRAINT OBPOS_TICKETLINES_TAX FOREIGN KEY (C_TAX_ID) REFERENCES C_TAX(C_TAX_ID)
);
CREATE UNIQUE INDEX OBPOS_TICKETLINES_TICKET ON OBPOS_TICKETLINES(OBPOS_TICKETS_ID, LINE);

CREATE TABLE OBPOS_PAYMENTS (
    OBPOS_PAYMENTS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_RECEIPTS_ID VARCHAR(32) NOT NULL,
    PAYMENT VARCHAR(1024) NOT NULL,
    TOTAL NUMERIC NOT NULL,
    TRANSID VARCHAR(1024),
    RETURNMSG BYTEA,
    CONSTRAINT OBPOS_PAYMENTS_PK PRIMARY KEY (OBPOS_PAYMENTS_ID),
    CONSTRAINT OBPOS_PAYMENTS_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_PAYMENTS_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_PAYMENTS_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_PAYMENTS_OBPOS_RECEIPTS FOREIGN KEY (OBPOS_RECEIPTS_ID) REFERENCES OBPOS_RECEIPTS(OBPOS_RECEIPTS_ID)
);
CREATE INDEX OBPOS_PAYMENTS_PAYMENT ON OBPOS_PAYMENTS(PAYMENT);
CREATE INDEX OBPOS_PAYMENTS_RECEIPTS_ID ON OBPOS_PAYMENTS(OBPOS_RECEIPTS_ID);

CREATE TABLE OBPOS_TAXLINES (
    OBPOS_TAXLINES_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_RECEIPTS_ID VARCHAR(32) NOT NULL,
    C_TAX_ID VARCHAR(32) NOT NULL,
    BASE NUMERIC NOT NULL,
    AMOUNT NUMERIC NOT NULL,
    CONSTRAINT OBPOS_TAXLINES_PK PRIMARY KEY (OBPOS_TAXLINES_ID),
    CONSTRAINT OBPOS_TAXLINES_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_TAXLINES_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_TAXLINES_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_TAXLINES_TAXES FOREIGN KEY (C_TAX_ID) REFERENCES C_TAX(C_TAX_ID),
    CONSTRAINT OBPOS_TAXLINES_RECEIPTS FOREIGN KEY (OBPOS_RECEIPTS_ID) REFERENCES OBPOS_RECEIPTS(OBPOS_RECEIPTS_ID)
);
CREATE INDEX OBPOS_TAXLINES_RECEIPTS ON OBPOS_TAXLINES(OBPOS_RECEIPTS_ID);

CREATE TABLE OBPOS_FLOORS (
    OBPOS_FLOORS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    IMAGE BYTEA,
    CONSTRAINT OBPOS_FLOORS_PK PRIMARY KEY (OBPOS_FLOORS_ID),
    CONSTRAINT OBPOS_FLOORS_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_FLOORS_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_FLOORS_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
);
CREATE UNIQUE INDEX OBPOS_FLOORS_NAME ON OBPOS_FLOORS(NAME);

CREATE OR REPLACE VIEW OBPOS_FLOORSVIEW AS
SELECT OBPOS_FLOORS_ID, AD_CLIENT_ID, AD_ORG_ID, ISACTIVE, CREATED, CREATEDBY, UPDATED, UPDATEDBY, NAME FROM OBPOS_FLOORS;

CREATE TABLE OBPOS_PLACES (
    OBPOS_PLACES_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    X NUMERIC(10,0) NOT NULL,
    Y NUMERIC(10,0) NOT NULL,
    OBPOS_FLOORS_ID VARCHAR(32) NOT NULL,
    CONSTRAINT OBPOS_PLACES_PK PRIMARY KEY (OBPOS_PLACES_ID),
    CONSTRAINT OBPOS_PLACES_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_PLACES_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_PLACES_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_PLACES_FLOORS FOREIGN KEY (OBPOS_FLOORS_ID) REFERENCES OBPOS_FLOORS(OBPOS_FLOORS_ID)
);
CREATE UNIQUE INDEX OBPOS_PLACES_NAME ON OBPOS_PLACES(NAME);

CREATE TABLE OBPOS_RESERVATIONS (
    OBPOS_RESERVATIONS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    DATENEW TIMESTAMP DEFAULT '2001-01-01 00:00:00' NOT NULL,
    TITLE VARCHAR(1024) NOT NULL,
    CHAIRS NUMERIC(10,0) NOT NULL,
    ISDONE CHAR(1) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    CONSTRAINT OBPOS_RESERV_PK PRIMARY KEY (OBPOS_RESERVATIONS_ID),
    CONSTRAINT OBPOS_RESERV_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_RESERV_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_RESERV_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
);
CREATE INDEX OBPOS_RESERVATIONS_DATENEW ON OBPOS_RESERVATIONS(DATENEW);

CREATE TABLE OBPOS_RESERVATION_CUSTOMERS (
    OBPOS_RESERVATION_CUSTOMERS_ID VARCHAR(32) NOT NULL,
    OBPOS_RESERVATIONS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    OBPOS_CUSTOMERS_ID VARCHAR(32) NOT NULL,
    CONSTRAINT OBPOS_RES_CUST_PK PRIMARY KEY (OBPOS_RESERVATION_CUSTOMERS_ID),
    CONSTRAINT OBPOS_RES_CUST_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_RES_CUST_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_RES_CUST_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT OBPOS_RES_CUST_RESERV FOREIGN KEY (OBPOS_RESERVATIONS_ID) REFERENCES OBPOS_RESERVATIONS(OBPOS_RESERVATIONS_ID),
    CONSTRAINT OBPOS_RES_CUST_CUST FOREIGN KEY (OBPOS_CUSTOMERS_ID) REFERENCES OBPOS_CUSTOMERS(OBPOS_CUSTOMERS_ID)
);

CREATE TABLE OBPOS_SHAREDTICKETS (
    OBPOS_SHAREDTICKETS_ID VARCHAR(32) NOT NULL,
    AD_CLIENT_ID character varying(32) NOT NULL,
    AD_ORG_ID character varying(32) NOT NULL,
    ISACTIVE character(1) NOT NULL DEFAULT 'Y'::bpchar,
    CREATED timestamp without time zone NOT NULL DEFAULT now(),
    CREATEDBY character varying(32) NOT NULL,
    UPDATED timestamp without time zone NOT NULL DEFAULT now(),
    UPDATEDBY character varying(32) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    PLACE VARCHAR(1024),
    CONTENT BYTEA,
    CONSTRAINT OBPOS_SHTICKETS_PK PRIMARY KEY(OBPOS_SHAREDTICKETS_ID),
    CONSTRAINT OBPOS_SHTICKETS_AD_CLIENT FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT(AD_CLIENT_ID),
    CONSTRAINT OBPOS_SHTICKETS_AD_ORG FOREIGN KEY (AD_ORG_ID) REFERENCES AD_ORG(AD_ORG_ID),
    CONSTRAINT OBPOS_SHTICKETS_ISACTIVE_CHK CHECK (ISACTIVE = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
);

CREATE OR REPLACE VIEW OBPOS_SHAREDTICKETSVIEW AS
SELECT OBPOS_SHAREDTICKETS_ID, AD_CLIENT_ID, AD_ORG_ID, ISACTIVE, CREATED, CREATEDBY, UPDATED, UPDATEDBY, NAME, PLACE FROM OBPOS_SHAREDTICKETS;
