//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.panels;

import com.openbravo.data.gui.JCounter;
import com.openbravo.data.gui.JLabelDirty;
import com.openbravo.data.gui.JListNavigator;
import com.openbravo.data.gui.JNavigator;
import com.openbravo.data.gui.JSaver;
import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;



/**
 *
 * @author adrianromero
 */
public class MaintenanceContainer extends JPanel {

    /** Creates new form JPanelTableEditor */
    public MaintenanceContainer() {

        initComponents();
    }

    public void init(MaintenancePanel maintenancepanel){

        // Add the filter panel
        Component c = maintenancepanel.getFilter();
        if (c != null) {
            c.applyComponentOrientation(getComponentOrientation());
            add(c, BorderLayout.NORTH);
        }

        // Add the editor
        c = maintenancepanel.getEditorComponent();
        if (c != null) {
            c.applyComponentOrientation(getComponentOrientation());
            container.add(c, BorderLayout.CENTER);
        }

        // el panel este
        ListCellRenderer cr = maintenancepanel.getListCellRenderer();
        if (cr != null) {
            JListNavigator nl = new JListNavigator(maintenancepanel.getBrowsableEditableData());
            nl.applyComponentOrientation(getComponentOrientation());
            if (cr != null) nl.setCellRenderer(cr);
            container.add(nl, java.awt.BorderLayout.LINE_START);
        }

        // add toolbar extras
        c = maintenancepanel.getToolbarExtras();
        if (c != null) {
            c.applyComponentOrientation(getComponentOrientation());
            toolbar.add(c);
        }

        // La Toolbar
        c = new JLabelDirty(maintenancepanel.getDirtyManager());
        c.applyComponentOrientation(getComponentOrientation());
        toolbar.add(c);
        c = new JCounter(maintenancepanel.getBrowsableEditableData());
        c.applyComponentOrientation(getComponentOrientation());
        toolbar.add(c);
        c = new JNavigator(maintenancepanel.getBrowsableEditableData(), maintenancepanel.getVectorer(), maintenancepanel.getComparatorCreator());
        c.applyComponentOrientation(getComponentOrientation());
        toolbar.add(c);
        c = new JSaver(maintenancepanel.getBrowsableEditableData());
        c.applyComponentOrientation(getComponentOrientation());
        toolbar.add(c);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        toolbar = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.BorderLayout());

        container.setLayout(new java.awt.BorderLayout());
        container.add(toolbar, java.awt.BorderLayout.NORTH);

        add(container, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
  
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables
    
}
